spring:
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    protocol: smtp
    username: info9216@gmail.com
    password: FLfS7K0QmynvjHGY

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: true

    #hibernate.ddl-auto: true
    show-sql: true
    generate-ddl: true
