
spring:
  mail:
    host: smtp-relay.sendinblue.com
    port: 587
    protocol: smtp
    username: info9216@gmail.com
    password: FLfS7K0QmynvjHGY

  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://postgres:5432/alpharesource
    username: postgres
    password: postgres!
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: true

    #hibernate.ddl-auto: true
    show-sql: true
    generate-ddl: true
  data:
    elasticsearch:
      host: elasticsearch
      port: 9200
  sql:
    init:
      mode: always
